config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  
  root 'tweets#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    validates :message, presence: true, length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def show
    @tweets = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end

  def edit
     @tweet = Tweet.find(params[:id])
  end

  def create
    message = params[:tweet][:message]
    tdate = Time.current
    @tweet = Tweet.new(message: message, tdate: tdate)
    if @tweet.save
      redirect_to '/', notice: 'ツイートしました.'
    else
     render 'new'
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to '/', notice: 'ツイートを削除しました.'
  end

  def update
    @tweet = Tweet.find(params[:id])
    message = params[:tweet][:message]
    tdate = params[:tweet][:tdate]
    @tweet.update(message: message, tdate: tdate) 
    redirect_to '/', notice: 'ツイートを更新しました.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>LikeTwitter</title>
  
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Like_Twitter</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Dosis:300,400,500,600,700">
    <link rel="stylesheet" href="application.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
      
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header>
      <div class="container">
        <div class="header-title">
          <%= link_to 'ホーム', root_path, class:"header-logo" %>
          <%= link_to 'モーメント', root_path, class:"header-logo" %>
          <%= link_to '通知', root_path, class:"header-logo" %>
          <%= link_to 'メッセージ', root_path, class:"header-logo" %>
          <img src="bird.PNG" class="header-icon">
        </div>
        <div class="header-menu">
          <ul class="tweet-btn">
            <li>
              <%= text_field_tag "#", "キーワードを検索", class: 'header-search-field' %>
            </li>     
            <li>
              <img src="12YbL9j9_400x400.jpg"class="header-prof-icon">
            </li>             
            <li>
              <%= link_to 'ツイート', new_tweet_path %>
            </li>
          </ul>
        </div>
      </div>
      
    </header>
      <div class="top-section gray-section">
    <div class="top-inner">
      
      <div class="container">
        <div class="top-description">
          <a href = "https://www.digitalcombatsimulator.com/en/"><h2>Initializin'....</h2></a>
          <p>Ready...?</p>
          
        </div>
      </div>
      <img src="12YbL9j9_400x400.jpg" class="top-prof-icon">
    </div>
    
  </div>

      </div>  
  
  <%= yield %>


  <footer>
    <div class="container">
      <div class="follow-us">
        <a href="https://www.facebook.com/" class="social-icon" target='_blank'>
          <span class="fa fa-facebook"></span>
        </a>
        <a href="https://twitter.com" class="social-icon" target='_blank'>
          <span class="fa fa-twitter"></span>
        </a>
      </div>
    </div>
  </footer>
    <script type="text/javascript" src="app/assets/javascripts/application.js"></script>
</body>
</html>

app/views/tweets/_form.html.erb
  <p><%= f.label :message, 'ツイート' %>
  <%= f.text_field :message %></p>
  <%= f.submit 'ツイート' %>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/edit.html.erb
<h1>ツイート編集</h1>

<%= form_for @tweet, :url=> {action: :update} do |f| %>
<%= render 'form', f: f %>
  ツイート日時: <%= @tweet.tdate %>
  <%= f.hidden_field :tdate %></p>

<% end %>

<%= link_to '戻る', root_path %>

app/views/tweets/index.html.erb
  <html>
    <head>
  
  <link rel="stylesheet" href="index.css">
  </head>
  <body>
    
        <div class="body-top">
          <div class="body-prof">
          <%= link_to 'ツイート', root_path, class:"body-logo" %>
          <%= link_to 'フォロー', root_path, class:"body-logo" %>
          <%= link_to 'フォロワー', root_path, class:"body-logo" %>
          <%= link_to 'いいね', root_path, class:"body-logo" %>
          <%= link_to 'プロフィールを編集', new_tweet_path, class: "body-logo" %>
          </div>
        </div>
<br>
<div class="container">
                      <div class="prof">
<ul>
  <h2>Usr_name</h2>
    <li>@usr_id</li>
    <br>
    <p>はまぐりはまぐり</p>
</ul>
    </div>

  <div class="tweet-table" align="center">
    <table border = 1 class="tw-table">
      <thead>
        <tr>
          <th>ツイート</th>
        </tr>
      </thead>

    <tbody>
        <% @tweets.each do |tweet| %>
          <tr>
            
            <td><img src="12YbL9j9_400x400.jpg"class="header-prof-icon"> <b>Usr_name</b> @Usr_id <align="right"><%= ((Time.current - tweet.tdate)/60).to_i %>分前
            <br>
            
            <h1><%= tweet.message %></h1>
            <p align ="right">
            <%= link_to '表示', tweet_path(tweet.id) %>
            <%= link_to '編集', edit_tweet_path(tweet.id) %>
            <%= link_to '削除', tweet_path(tweet.id), method: :delete, data: { confirm: '本当に削除してもよろしいですか?' } %></p>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    </div>
        


    </div>


  
    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>
    <br>
    </body>
    <html>

app/views/tweets/new.html.erb
<div align="center">
<% if @tweet.errors.present? %>
  <h3>エラーがあります。</h3>
    <ul> <% @tweet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li> 
    <% end %>
  </ul>
<% end %>


<%= form_for @tweet, url: {action: :create} do |f| %>
<%= render 'form',f: f %>
<% end %>

<%= link_to '戻る', root_path %>
</div>

app/views/tweets/show.html.erb
<p>ツイート: <%= @tweets.message %></p>

<p>ツイート日時: <%= @tweets.tdate %></p>

<%= link_to '戻る', '/' %>